"""Generate src/sprites.h from the PNG artwork in sprites/."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent
SPRITES = ROOT / "sprites"
OUTPUT = ROOT / "src" / "sprites.h"
OUTPUT_SIZE = (64, 64)

GROUPS = (
    ("IDLE", (SPRITES / "cat" / "cat.png",)),
    ("SLEEP", tuple(SPRITES / "cat-sleep" / f"cat-sleep_{i}.png" for i in range(1, 5))),
    ("HAPPY", (SPRITES / "cat-happy" / "cat-happy.png",)),
    ("SAD", (SPRITES / "cat-sad" / "cat-sad.png",)),
    ("PET", tuple(SPRITES / "cat-pet" / f"cat-pet{i}.png" for i in range(1, 9))),
    ("EAT", tuple(SPRITES / "cat-eat" / f"cat-eat{i}.png" for i in range(1, 23))),
    (
        "MUSIC",
        tuple(
            SPRITES / "cat-listen-music" / f"cat-music-listen{i}.png"
            for i in range(1, 9)
        ),
    ),
)


def identifier(path: Path) -> str:
    return path.stem.lower().replace("-", "_")


def rgb565_pixels(path: Path) -> list[int]:
    image = Image.open(path).convert("RGBA")
    image = image.resize(OUTPUT_SIZE, Image.Resampling.NEAREST)
    canvas = Image.new("RGBA", OUTPUT_SIZE, (0, 0, 0, 255))
    canvas.alpha_composite(image)

    pixels = (
        canvas.get_flattened_data()
        if hasattr(canvas, "get_flattened_data")
        else canvas.getdata()
    )
    values = []
    for red, green, blue, _alpha in pixels:
        values.append(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3))
    return values


def main() -> None:
    lines = [
        "#ifndef SPRITES_H",
        "#define SPRITES_H",
        "",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by generate_sprites.py from 32x32 PNG artwork.",
        "// Images are nearest-neighbor scaled to 64x64 and stored as RGB565.",
        "",
        "static const uint16_t SPRITE_W = 64;",
        "static const uint16_t SPRITE_H = 64;",
        "",
    ]

    for _group_name, paths in GROUPS:
        for path in paths:
            if not path.exists():
                raise FileNotFoundError(path)

            name = identifier(path)
            pixels = rgb565_pixels(path)
            lines.append(f"// {path.relative_to(SPRITES).as_posix()}")
            lines.append(f"static const uint16_t {name}[{len(pixels)}] PROGMEM = {{")
            for offset in range(0, len(pixels), 16):
                row = ",".join(f"0x{value:04X}" for value in pixels[offset : offset + 16])
                lines.append(f"  {row},")
            lines.extend(("};", ""))

    for group_name, paths in GROUPS:
        lines.append(f"static const uint16_t* const {group_name}_FRAMES[] = {{")
        lines.extend(f"  {identifier(path)}," for path in paths)
        lines.append("};")
        lines.append(
            f"static const uint8_t {group_name}_FRAME_COUNT = "
            f"sizeof({group_name}_FRAMES) / sizeof({group_name}_FRAMES[0]);"
        )
        lines.append("")

    lines.extend(("#endif", ""))
    OUTPUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
